LevantamientoDeRed/Entities/Gpon.cs
namespace LevantamientoDeRed.Entities
{
    public class Gpon : Base
    {
        public string Nombre { get; set; }
        public string? PosteId { get; set; }
        public virtual Poste? Poste { get; set; }
        public ICollection<Mufa> Mufas { get; set; } = new List<Mufa>();
    }
}

LevantamientoDeRed/Controllers/API/GponsController.cs
using AutoMapper;
using LevantamientoDeRed.Dto;
using LevantamientoDeRed.Dto.Gpon;
using LevantamientoDeRed.Entities;
using LevantamientoDeRed.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace LevantamientoDeRed.Controllers.API
{
    /// <summary>
    /// Endpoints para la API de GPONs
    /// </summary>
    [Route("api/[controller]")]
    [ApiController]
    public class GponsController : ControllerBase
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly ILogger<CablesController> _logger;

        /// <summary>
        /// Constructor principal para la API de GPONs
        /// </summary>
        /// <param name="unitOfWork"></param>
        /// <param name="mapper"></param>
        /// <param name="logger"></param>
        public GponsController(IUnitOfWork unitOfWork, IMapper mapper, ILogger<CablesController> logger)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _logger = logger;
        }

        /// <summary>
        /// Endpoint para la creacion de un GPON
        /// </summary>
        /// <param name="dTO"></param>
        /// <returns></returns>
        [ProducesResponseType(StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [HttpPost("crear")]
        public async Task<IActionResult> Create(CrearGponDto dto)
        {
            try
            {
                if (!ModelState.IsValid)
                    return BadRequest(ModelState);

                var gpon = _mapper.Map<Gpon>(dto);
                gpon.PosteId = string.IsNullOrEmpty(dto.PosteId) ? null : dto.PosteId;

                _unitOfWork.Repositorio<Gpon>().Crear(gpon);

                await _unitOfWork.SaveChangesAsync();

                return StatusCode(StatusCodes.Status201Created);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible crear el registro del GPON: {Message}", ex.Message);
                return BadRequest($"No fue posible crear el registro del GPON. Puede usar el siguiente codigo {ex.HResult} para solicitar ayuda.");
            }
        }
        
        /// <summary>
        /// Endpoint para la modificación de un GPON
        /// </summary>
        /// <param name="dTO"></param>
        /// <returns></returns>
        [ProducesResponseType(StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [HttpPut("editar")]
        public async Task<IActionResult> Edit(CrearGponDto dto)
        {
            try
            {
                if (!ModelState.IsValid)
                    return BadRequest(ModelState);

                var gpon = _mapper.Map<Gpon>(dto);
                gpon.PosteId = string.IsNullOrEmpty(dto.PosteId) ? null : dto.PosteId;

                _unitOfWork.Repositorio<Gpon>().Actualizar(gpon);

                await _unitOfWork.SaveChangesAsync();

                return StatusCode(StatusCodes.Status201Created);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible modificar el registro del GPON: {Message}", ex.Message);
                return BadRequest($"No fue posible modificar el registro del GPON. Puede usar el siguiente codigo {ex.HResult} para solicitar ayuda.");
            }
        }

        /// <summary>
        /// Endpoint para obtener un GPON por su ID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [ProducesResponseType(typeof(MufaDto), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [HttpGet("{id}")]
        public async Task<ActionResult<MufaDto>> Get(string id)
        {
            try
            {
                var gpon = await _unitOfWork.Repositorio<Gpon>().ObtenerPorIdAsync(id, includeProperties: "Poste");

                if (gpon == null)
                    return NotFound();

                var result = _mapper.Map<GponDto>(gpon);

                return Ok(result);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible crear el registro del GPON: {Message}", ex.Message);
                return BadRequest($"No fue posible crear el registro del GPON. Puede usar el siguiente codigo {ex.HResult} para solicitar ayuda.");
            }
        }

        /// <summary>
        /// Endpoint para obtener una lista de GPONs
        /// </summary>
        /// <returns></returns>
        [ProducesResponseType(typeof(List<GponDto>), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(List<GponDto>), StatusCodes.Status400BadRequest)]
        [HttpGet()]
        public async Task<ActionResult<List<GponDto>>> Get()
        {
            try
            {
                var gpons = await _unitOfWork.Repositorio<Gpon>().ObtenerTodosAsync(includeProperties: "Poste");
                var results = _mapper.Map<List<GponDto>>(gpons);

                return Ok(results);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible crear el registro del GPON: {Message}", ex.Message);
                return BadRequest($"No fue posible crear el registro del GPON. Puede usar el siguiente codigo {ex.HResult} para solicitar ayuda.");
            }
        }
    }
}

LevantamientoDeRed/Controllers/MVC/GponsController.cs
using AutoMapper;
using LevantamientoDeRed.Dto;
using LevantamientoDeRed.Entities;
using LevantamientoDeRed.Repositories;
//using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LevantamientoDeRed.Controllers.MVC
{
    public class GponsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly ILogger<UsuariosController> _logger;

        public GponsController(IUnitOfWork unitOfWork, IMapper mapper, ILogger<UsuariosController> logger)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _logger = logger;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Crear()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Eliminar(string id)
        {
            try
            {
                if (id == null)
                {
                    ViewData["error_obtener"] = "No fue posible obtener los datos del GPON";
                    return View();
                }

                var gpon = await _unitOfWork.Repositorio<Gpon>().ObtenerPorIdAsync(id);

                if (gpon == null)
                {
                    ViewData["error_obtener"] = "No fue posible obtener los datos del GPON";
                    return View();
                }

                var result = _mapper.Map<GponDto>(gpon);

                return View(result);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible obtener los datos del GPON: {Message}", ex.Message);
                ViewData["error_obtener"] = "No fue posible obtener los datos del GPON";
                return View();
            }
        }

        [ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> ConfirmarEliminar(string id)
        {
            try
            {
                if (id == null)
                {
                    ViewData["error_obtener"] = "No fue posible obtener los datos del GPON";
                    return View();
                }

                var gpon = await _unitOfWork.Repositorio<Gpon>().ObtenerPorIdAsync(id, rastreo: false);

                if (gpon == null)
                {
                    ViewData["error_obtener"] = "No fue posible obtener los datos del GPON";
                    return View();
                }

                _unitOfWork.Repositorio<Gpon>().Eliminar(gpon);

                if (await _unitOfWork.SaveChangesAsync())
                    return View(nameof(Index));

                ViewData["error_obtener"] = "No fue posible eliminar los datos del poste";
                return View(_mapper.Map<GponDto>(gpon));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible eliminar o obtener los datos del poste: {Message}", ex.Message);
                ViewData["error_obtener"] = "No fue posible eliminar o obtener los datos del poste";
                return View();
            }
        }
    }
}

LevantamientoDeRed/Views/Gpons/Crear.cshtml
@{
    ViewData["Title"] = "Crear GPON";
}

<div class="container-fluid px-4" style="display: grid">
    <h1 class="mt-4">Crear GPON</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Tablero</a></li>
        <li class="breadcrumb-item"><a href="/Postes">Postes</a></li>
        <li class="breadcrumb-item"><a href="/Gpons">Mapa de GPONs</a></li>
        <li class="breadcrumb-item active">Crear GPON</li>
    </ol>
    @* <div class="btn-group mb-4" role="group">
        <input type="checkbox" class="btn-check" id="drawLinesCheckbox" autocomplete="off">
        <label class="btn btn-outline-primary" for="drawLinesCheckbox" id="drawLinesCheckboxLabel">Agregar</label>
    </div> *@
    <div class="btn-group mb-4" role="group" aria-label="Basic mixed styles example">
        <button type="button" id="btnGuardar" class="btn btn-success" onclick="showCreateModal()">Crear Nuevo GPON</button>
    </div>

    @* <div class="card">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Crear GPON
        </div>
        <div class="card-body">
            <div id="map" style="height: 500px"></div>
        </div>
    </div> *@
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_GoogleMapsScriptsPartial");
        await Html.RenderPartialAsync("_PostesControllerScriptsPartial");
        await Html.RenderPartialAsync("_GponsControllerScriptsPartial");
    }

    <script>
        let map;
        let gpon = {};

        async function initMap() {
            const position = { lat: 13.924394865271614, lng: -89.849635478908 };
            const { Map } = await google.maps.importLibrary("maps");

            map = new Map(document.getElementById("map"), {
                zoom: 15,
                center: position,
                mapId: "DEMO_MAP_ID",
            });

            const btnGuardar = document.getElementById("btnGuardar");

            // drawLinesCheckbox.addEventListener("change", () => {
            //     drawEnabled = drawLinesCheckbox.checked;

            //     if (drawEnabled) {
            //         drawLinesCheckboxLabel.innerHTML = "Dejar de agregar"; // Cambiar el texto del botón
            //         btnGuardar.disabled = true;
            //     } else {
            //         drawLinesCheckboxLabel.innerHTML = "Agregar"; // Cambiar el texto del botón
            //         btnGuardar.disabled = false;
            //     }
            // });

            btnGuardar.addEventListener("click", async () => {
                await showCreateModal();
            })

            map.addListener("click", (e) => {
                if (drawEnabled) {
                    gpon = e.latLng; // Agregar las coordenadas del punto a la matriz
                    add(e.latLng);
                }
            });
        }

        function add(location) {
            const newGpon = new google.maps.Marker({
                position: location,
                map: map,
                title: "Nuevo Punto",
                icon: "https://maps.google.com/mapfiles/ms/icons/red-dot.png",
            });
        }

        async function showCreateModal() {
            const postes = (await obtenerPostes()).map((poste) => `<option value="${poste.id}">${poste.nombre}</option>`).join();

            const { value: formValues } = await Swal.fire({
                title: 'Datos del nuevo GPON',
                html:
                    // Input del nombre
                    '<div class="form-floating mb-3">' +
                    '<input type="text" class="form-control" id="gpon-nombre" placeholder="Ingrese el nombre de la mufa" required>' +
                    '<label for="floatingInput">Nombre</label>' +
                    '</div>' +
                    // Select de tipos de mufas
                    '<div class="form-floating mb-3">' +
                    '  <select class="form-select" id="postes-list" required>' +
                    '    <option value="">-- No asignar aun --</option>' +
                    postes +
                    '  </select>' +
                    '  <label for="postes-list">Postes</label>' +
                    '</div>',
                focusConfirm: false,
                showCancelButton: true,
                preConfirm: () => {
                    return [
                        document.getElementById('gpon-nombre').value,
                        document.getElementById('postes-list').value,
                    ]
                }
            })

            if (formValues) {
                const toSend = {
                    nombre: formValues[0],
                    posteId: formValues[1]
                };

                await AgregarGpon(toSend)
            }
        }

        //initMap();
    </script>
}

LevantamientoDeRed/Views/Gpons/Eliminar.cshtml
@using LevantamientoDeRed.Dto;
@model GponDto

@{
    ViewData["Title"] = "Eliminar GPON";
}

<div class="bg-secondary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-7">
                            <div class="card shadow-lg border-0 rounded-lg mt-5 mb-5">
                                <div class="card-header">
                                    <h3 class="text-center font-weight-light my-4">Eliminar GPON</h3>
                                    @if (ViewData["error_obtener"] is not null)
                                    {
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Ocurri&oacute; un error</h4>
                                            <p>@ViewData["error_obtener"]</p>
                                        </div>
                                        <a asp-action="Index" asp-controller="Gpons">Volver</a>
                                    }
                                </div>
                                <div class="card-body">
                                    @if (ViewData["error_obtener"] is null)
                                    {
                                        <div>
                                            <dl class="row">
                                                <dt class="col-sm-2">
                                                    @Html.DisplayNameFor(model => model.Id)
                                                </dt>
                                                <dd class="col-sm-10">
                                                    @Html.DisplayFor(model => model.Id)
                                                </dd>
                                                <dt class="col-sm-2">
                                                    @Html.DisplayNameFor(model => model.Nombre)
                                                </dt>
                                                <dd class="col-sm-10">
                                                    @Html.DisplayFor(model => model.Nombre)
                                                </dd>
                                                <dt class="col-sm-2">
                                                    @Html.DisplayNameFor(model => model.PosteId)
                                                </dt>
                                                <dd class="col-sm-10">
                                                    @Html.DisplayFor(model => model.PosteId)
                                                </dd>
                                            </dl>

                                            <form asp-action="Eliminar" asp-controller="Gpons">
                                                <input type="hidden" asp-for="Id" />
                                                <input type="submit" value="Eliminar" class="btn btn-danger" />
                                                <a asp-action="Index" asp-controller="Gpons" class="btn btn-secondary">Volver</a>
                                            </form>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</div>

LevantamientoDeRed/Views/Gpons/Index.cshtml
@{
    ViewData["Title"] = "Mapa de GPONs";
}

<div class="container-fluid px-4" style="display: grid">
    <h1 class="mt-4">Mapa de GPONs</h1>

    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Tablero</a></li>
        <li class="breadcrumb-item"><a href="/Postes">Postes</a></li>
        <li class="breadcrumb-item active">Mapa de GPONs</li>
    </ol>

    @if (User.IsInRole("Administrador") || User.IsInRole("Jefe"))
    {
        <div class="btn-group mb-4" role="group" aria-label="Basic mixed styles example">
            <a asp-action="Crear" class="btn btn-success">Crear</a>
            <button id="editarButtonElement" type="button" class="btn btn-info">Editar</button>

            <button id="eliminarButtonElement" type="button" class="btn btn-danger">Eliminar</button>
        </div>
    }
    else if (User.IsInRole("Tecnico"))
    {
        <div class="btn-group mb-4" role="group" aria-label="Basic mixed styles example">
            <a asp-action="Crear" class="btn btn-success">Crear</a>
        </div>
    }

    <div class="form-floating mb-4">
        <select id="selectElement" class="form-select">
            <option selected value="0">Todos</option>
        </select>
        <label for="selectElement">Seleccionar</label>
    </div>

    <div class="card">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Mapa de GPONs
        </div>
        <div class="card-body">
            <div id="map" style="height: 500px"></div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_GoogleMapsScriptsPartial");
        await Html.RenderPartialAsync("_PostesControllerScriptsPartial");
        await Html.RenderPartialAsync("_GponsControllerScriptsPartial");
    }

    <script async>
        let map;
        let marcadores = [];

        async function initMap() {
            const position = { lat: 13.924394865271614, lng: -89.849635478908 };
            const { Map } = await google.maps.importLibrary("maps");
            const gpons = await ObtenerGpons();

            map = new Map(document.getElementById("map"), {
                zoom: 15,
                center: position,
                mapId: "DEMO_MAP_ID",
            });

            gpons.map((gpon) => {
                draw(gpon)
            });

            rellenarElementoSelectGpons(gpons);

            document.getElementById("selectElement").addEventListener("change", async () => {
                const selectElement = document.getElementById("selectElement");

                deleteAllMarkers();

                if (selectElement.value === "0") {
                    gpons.map((gpon) => {
                        draw(gpon)
                    });
                } else {
                    const fromApi = await obtenerGpon(selectElement.value);

                    draw(fromApi);
                }
            });

            document.getElementById("eliminarButtonElement").addEventListener("click", async () => {
                const selectElement = document.getElementById("selectElement");
                const URL_BASE = `${window.location.protocol}//${window.location.hostname}${PORT}/Gpons/Eliminar`;

                if (selectElement.value !== "0") {
                    window.location.href = URL_BASE + "/" + selectElement.value;
                }
                else {
                    await Swal.fire(
                        'Advertencia',
                        'Debe seleccionar un GPON para realizar esta accion',
                        'warning'
                    )
                }
            });

            document.getElementById("editarButtonElement").addEventListener("click", async () => {
                const selectElement = document.getElementById("selectElement");

                if (selectElement.value !== "0") {
                    showEditModal(selectElement.value);
                }
                else {
                    await Swal.fire(
                        'Advertencia',
                        'Debe seleccionar un GPON para realizar esta accion',
                        'warning'
                    )
                }
            });
        }

        function draw(gpon) {
            const latLng = {
                lat: gpon.latitud,
                lng: gpon.longitud
            };
            const imageUrl = "\logo_gpon.png";
            const newGpon = new google.maps.Marker({
                position: latLng,
                map: map,
                title: gpon.nombre,
                icon: {
                    url: imageUrl,
                    scaledSize: new google.maps.Size(30, 30) // Ajusta el tamaño según tus necesidades
                },
            });
            marcadores.push(newGpon);
        }

        // Elimina todos los marcadores cuando se llama
        function deleteAllMarkers() {
            for (var i = 0; i < marcadores.length; i++) {
                marcadores[i].setMap(null);
            }

            // Limpia el array de marcadores
            marcadores = [];
        }

        async function showEditModal(id) {
            let toEdit = await obtenerGpon(id);

            const postes = (await obtenerPostes()).map((poste) => {
                if (poste.id === toEdit.posteId) {
                    return `<option value="${poste.id}" selected>${poste.nombre}</option>`;
                }

                return `<option value="${poste.id}">${poste.nombre}</option>`;
            }).join();

            const { value: formValues } = await Swal.fire({
                title: 'Datos del GPON',
                html:
                    // Input del nombre
                    '<div class="form-floating mb-3">' +
                    `<input type="text" value="${toEdit.nombre}" class="form-control" id="gpon-nombre" placeholder="Ingrese el nombre de la mufa" required>` +
                    '<label for="floatingInput">Nombre</label>' +
                    '</div>' +
                    // Select de tipos de mufas
                    '<div class="form-floating mb-3">' +
                    '  <select class="form-select" id="postes-list" required>' +
                    '    <option value="">-- No asignar aun --</option>' +
                    postes +
                    '  </select>' +
                    '  <label for="postes-list">Postes</label>' +
                    '</div>' +
                    `<input type="hidden" value="${toEdit.id}" class="form-control" id="mufa-id">`,
                focusConfirm: false,
                showCancelButton: true,
                preConfirm: () => {
                    return [
                        document.getElementById('gpon-nombre').value,
                        document.getElementById('postes-list').value,
                    ]
                }
            })

            if (formValues) {
                toEdit.nombre = formValues[0];
                toEdit.posteId = formValues[1];
                await EditarGpon(toEdit)
                location.reload(true);
            }
        }

        initMap();
    </script>
}