LevantamientoDeRed/Entities/Poste.cs
using NetTopologySuite.Geometries;

namespace LevantamientoDeRed.Entities
{
    public class Poste : Base
    {
        public string Nombre { get; set; }
        public Point? Coordenadas { get; set; }

        public ICollection<Gpon> Gpons { get; set; } = new List<Gpon>();
        public ICollection<Mufa> Mufas { get; set; } = new List<Mufa>();
    }
}

LevantamientoDeRed/Controllers/API/PostesController.cs
using AutoMapper;
using LevantamientoDeRed.Dto;
using LevantamientoDeRed.Entities;
using LevantamientoDeRed.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.JSInterop.Infrastructure;

namespace LevantamientoDeRed.Controllers.API
{
    /// <summary>
    /// Endpoints para la API de Postes
    /// </summary>
    [Route("api/[controller]")]
    [ApiController]
    public class PostesController : ControllerBase
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly ILogger<PostesController> _logger;

        /// <summary>
        /// Constructor principal para la API de Postes
        /// </summary>
        /// <param name="unitOfWork"></param>
        /// <param name="mapper"></param>
        /// <param name="logger"></param>
        public PostesController(IUnitOfWork unitOfWork, IMapper mapper, ILogger<PostesController> logger)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _logger = logger;
        }

        /// <summary>
        /// Endpoint para la creacion de un Poste
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [ProducesResponseType(StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [HttpPost("crear")]
        public async Task<IActionResult> Create(CrearPosteDto dto)
        {
            try
            {
                if (!ModelState.IsValid)
                    return BadRequest(ModelState);

                var poste = _mapper.Map<Poste>(dto);

                _unitOfWork.Repositorio<Poste>().Crear(poste);

                await AgregarOEditarGpon(poste, dto.GponId);
                await AgregarOEditarMufa(poste, dto.MufaId);
                await _unitOfWork.SaveChangesAsync();

                return StatusCode(StatusCodes.Status201Created);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible crear el registro del poste: {Message}", ex.Message);
                return BadRequest($"No fue posible crear el registro del poste. Puede usar el siguiente codigo {ex.HResult} para solicitar ayuda.");
            }
        }

        /// <summary>
        /// Endpoint para la edicion de un Poste
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [HttpPut("editar")]
        public async Task<IActionResult> Edit(CrearPosteDto dto)
        {
            try
            {
                if (!ModelState.IsValid)
                    return BadRequest(ModelState);

                var posteEntity = await _unitOfWork.Repositorio<Poste>().ObtenerPorIdAsync(dto.Id, "Gpons,Mufas");

                if (posteEntity == null)
                {
                    ModelState.AddModelError("PosteId", "Los datos del poste no existen o no estan disponibles.");
                    return BadRequest(ModelState);
                }

                var poste = _mapper.Map(dto, posteEntity);

                _unitOfWork.Repositorio<Poste>().Actualizar(poste);

                await AgregarOEditarGpon(poste, dto.GponId);
                await AgregarOEditarMufa(poste, dto.MufaId);
                await _unitOfWork.SaveChangesAsync();

                return StatusCode(StatusCodes.Status204NoContent);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible crear el registro del poste: {Message}", ex.Message);
                return BadRequest($"No fue posible crear el registro del poste. Puede usar el siguiente codigo {ex.HResult} para solicitar ayuda.");
            }
        }

        /// <summary>
        /// Endpoint para obtener una lista de Postes
        /// </summary>
        /// <returns></returns>
        [ProducesResponseType(typeof(List<PosteDto>), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [HttpGet]
        public async Task<ActionResult<List<PosteDto>>> ObtenerPostes()
        {
            try
            {
                var postes = await _unitOfWork.PosteRepositorio.GetPostes(false);
                var results = _mapper.Map<List<PosteDto>>(postes);
                return Ok(results);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible crear el registro del poste: {Message}", ex.Message);
                return BadRequest($"No fue posible crear el registro del poste. Puede usar el siguiente codigo {ex.HResult} para solicitar ayuda.");
            }
        }

        /// <summary>
        /// Endpoint para obtener un Poste por su ID
        /// </summary>
        /// <param name="posteId"></param>
        /// <returns></returns>
        [ProducesResponseType(typeof(PosteDto), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [HttpGet("{posteId}")]
        public async Task<ActionResult<PosteDto>> ObtenerPoste(string posteId)
        {
            try
            {
                var poste = await _unitOfWork.PosteRepositorio.GetPosteById(posteId, false);

                if (poste == null)
                    return NotFound();

                var result = _mapper.Map<PosteDto>(poste);
                return Ok(result);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible crear el registro del poste: {Message}", ex.Message);
                return BadRequest($"No fue posible crear el registro del poste. Puede usar el siguiente codigo {ex.HResult} para solicitar ayuda.");
            }
        }

        /// <summary>
        /// Agrega o edita la relacion 1 a 1 entre un GPON y un Poste
        /// </summary>
        /// <param name="poste"></param>
        /// <param name="gponId"></param>
        /// <returns></returns>
        private async Task AgregarOEditarGpon(Poste poste, string? gponId)
        {
            if (!string.IsNullOrEmpty(gponId))
            {
                var gpon = await _unitOfWork.Repositorio<Gpon>().ObtenerPorIdAsync(id: gponId, rastreo: true);

                if (gpon != null)
                {
                    gpon.PosteId = poste.Id;
                }
            }
            else
            {
                gponId = poste.Gpons.FirstOrDefault()?.Id;

                if (!string.IsNullOrEmpty(gponId))
                {
                    var gpon = await _unitOfWork.Repositorio<Gpon>().ObtenerPorIdAsync(id: gponId, rastreo: true);

                    if (gpon != null)
                    {
                        gpon.PosteId = null;
                    }
                }
            }
        }

        /// <summary>
        /// Agrega o edita la relacion 1 a 1 entre una Mufa y un Poste
        /// </summary>
        /// <param name="poste"></param>
        /// <param name="mufaId"></param>
        /// <returns></returns>
        private async Task AgregarOEditarMufa(Poste poste, string? mufaId)
        {
            if (!string.IsNullOrEmpty(mufaId))
            {
                var mufa = await _unitOfWork.Repositorio<Mufa>().ObtenerPorIdAsync(id: mufaId, rastreo: true);

                if (mufa != null)
                {
                    mufa.PosteId = poste.Id;
                }
            }
            else
            {
                mufaId = poste.Mufas.FirstOrDefault()?.Id;

                if (!string.IsNullOrEmpty(mufaId))
                {
                    var mufa = await _unitOfWork.Repositorio<Mufa>().ObtenerPorIdAsync(id: mufaId, rastreo: true);

                    if (mufa != null)
                    {
                        mufa.PosteId = null;
                    }
                }
            }
        }
    }
}

LevantamientoDeRed/Controllers/PostesController.cs
using AutoMapper;
using LevantamientoDeRed.Dto;
using LevantamientoDeRed.Entities;
using LevantamientoDeRed.Repositories;
//using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LevantamientoDeRed.Controllers
{
    public class PostesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly ILogger<UsuariosController> _logger;

        public PostesController(IUnitOfWork unitOfWork, IMapper mapper, ILogger<UsuariosController> logger)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _logger = logger;
        }
        // GET: PostesController
        public ActionResult Index()
        {
            return View();
        }

        // GET: PostesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PostesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PostesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PostesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PostesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PostesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PostesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //Vistas de postes

        [HttpGet]
        public ActionResult Crear()
        {
            return View();
        }


        [HttpGet]
        public async Task<ActionResult> Eliminar(string? id)
        {
            try
            {
                if (id == null)
                {
                    ViewData["error_obtener_poste"] = "No fue posible obtener los datos del poste";
                    return View();
                }

                var poste = await _unitOfWork.Repositorio<Poste>().ObtenerPorIdAsync(id, rastreo: false);

                if (poste == null)
                {
                    ViewData["error_obtener_poste"] = "No fue posible obtener los datos del poste";
                    return View();
                }

                var result = _mapper.Map<PosteDto>(poste);

                return View(result);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible obtener los datos del poste: {Message}", ex.Message);
                ViewData["error_obtener_poste"] = "No fue posible obtener los datos del poste";
                return View();
            }
        }
        
        
        [ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> ConfirmarEliminar(string? id)
        {
            try
            {
                if (id == null)
                {
                    ViewData["error_obtener_poste"] = "No fue posible obtener los datos del poste";
                    return View();
                }

                var poste = await _unitOfWork.Repositorio<Poste>().ObtenerPorIdAsync(id, rastreo: false);

                if (poste == null)
                {
                    ViewData["error_obtener_poste"] = "No fue posible obtener los datos del poste";
                    return View();
                }

                _unitOfWork.Repositorio<Poste>().Eliminar(poste);

                if (await _unitOfWork.SaveChangesAsync())
                    return View(nameof(Index));

                ViewData["error_obtener_poste"] = "No fue posible eliminar los datos del poste";
                return View(_mapper.Map<PosteDto>(poste));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No fue posible eliminar o obtener los datos del poste: {Message}", ex.Message);
                ViewData["error_obtener_poste"] = "No fue posible eliminar o obtener los datos del poste";
                return View();
            }
        }
    }
}

LevantamientoDeRed/Views/Postes/Crear.cshtml
@{
    ViewData["Title"] = "Crear poste";
}

<div class="container-fluid px-4" style="display: grid">
    <h1 class="mt-4">Crear poste </h1>

    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Tablero</a></li>
        <li class="breadcrumb-item"><a href="/Postes">Postes</a></li>
        <li class="breadcrumb-item active">Crear poste </li>
    </ol>

    <div class="btn-group mb-4" role="group">
        <input type="checkbox" class="btn-check" id="drawLinesCheckbox" autocomplete="off">
        <label class="btn btn-outline-primary" for="drawLinesCheckbox" id="drawLinesCheckboxLabel">Agregar Poste</label>
    </div>

    <div class="btn-group mb-4" role="group" aria-label="Basic mixed styles example">
        <button type="button" id="btnGuardarPoste" class="btn btn-success" disabled>Guardar Poste</button>
    </div>

    <div class="card">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Crear poste 
        </div>
        <div class="card-body">
            <div id="map" style="height: 500px"></div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_GoogleMapsScriptsPartial");
        await Html.RenderPartialAsync("_PostesControllerScriptsPartial");
        await Html.RenderPartialAsync("_MufasControllerScriptsPartial");
        await Html.RenderPartialAsync("_GponsControllerScriptsPartial");
    }

    <script>
        let map;
        let poste = {};
        let marcadores = [];

        async function initMap() {
            const position = { lat: 13.924394865271614, lng: -89.849635478908 };
            const { Map } = await google.maps.importLibrary("maps");

            map = new Map(document.getElementById("map"), {
                zoom: 15,
                center: position,
                mapId: "DEMO_MAP_ID",
            });

            const btnGuardarPoste = document.getElementById("btnGuardarPoste");

            drawLinesCheckbox.addEventListener("change", () => {
                drawEnabled = drawLinesCheckbox.checked;

                if (drawEnabled) {
                    drawLinesCheckboxLabel.innerHTML = "Dejar de agregar Postes"; // Cambiar el texto del botón
                    btnGuardarPoste.disabled = true;
                } else {
                    //saveLastDrawnPolyline(); // Al desactivar, guardar la línea dibujada
                    drawLinesCheckboxLabel.innerHTML = "Agregar Poste"; // Cambiar el texto del botón
                    btnGuardarPoste.disabled = false;
                }
            });

            btnGuardarPoste.addEventListener("click", async () => {
                await showCreatePosteModal();
            })

            map.addListener("click", (e) => {
                if (drawEnabled) {
                    deleteAllMarkers()
                    poste = e.latLng; // Agregar las coordenadas del punto a la matriz
                    addPoste(poste);
                }
            });
        }

        function addPoste(location) {
            const newPoste = new google.maps.Marker({
                position: location,
                map: map,
                title: "Nuevo Punto",
                icon: "https://maps.google.com/mapfiles/ms/icons/red-dot.png",
            });

            marcadores.push(newPoste);
        }

        function deleteAllMarkers() {
            for (var i = 0; i < marcadores.length; i++) {
                marcadores[i].setMap(null);
            }

            // Limpia el array de marcadores
            marcadores = [];
        }

        async function showCreatePosteModal() {
            const mufas = (await ObtenerMufas()).map((mufa) => `<option value="${mufa.id}">${mufa.nombre}</option>`).join();
            const gpons = (await ObtenerGpons()).map((gpon) => `<option value="${gpon.id}">${gpon.nombre}</option>`).join();

            const { value: formValues } = await Swal.fire({
                title: 'Datos del nuevo poste',
                html:
                    // Input del nombre del poste
                    '<div class="form-floating mb-3">' +
                    '<input type="text" class="form-control" id="poste-nombre" placeholder="Ingrese el nombre del poste" required>' +
                    '<label for="floatingInput">Nombre Del Poste</label>' +
                    '</div>' +
                    // Select de mufas
                    '<div class="form-floating mb-3">' +
                    '  <select class="form-select" id="mufas-list" >' +
                    '    <option value="" selected>-- No agregar aun --</option>' +
                    mufas +
                    '  </select>' +
                    '  <label for="mufa-list">Seleccione mufa</label>' +
                    '</div>'+
                    // Select de GPONs
                    '<div class="form-floating mb-3">' +
                    '  <select class="form-select" id="gpons-list" >' +
                    '    <option value="" selected>-- No agregar aun --</option>' +
                    gpons +
                    '  </select>' +
                    '  <label for="gpons-list">Seleccione GPON</label>' +
                    '</div>',
                focusConfirm: false,
                showCancelButton: true,
                preConfirm: () => {
                    return [
                        document.getElementById('poste-nombre').value,
                        document.getElementById('mufas-list').value,
                        document.getElementById('gpons-list').value,
                    ]
                }
            })

            if (formValues) {
                const posteToSend = {
                    nombre: formValues[0],
                    mufaId: formValues[1],
                    gponId: formValues[2],
                    longitud: poste.lng(),
                    latitud: poste.lat()
                };

                await AgregarPoste(posteToSend);
            }
        }

        initMap();
    </script>
}

LevantamientoDeRed/Views/Postes/Eliminar.cshtml
@using LevantamientoDeRed.Dto;
@model PosteDto

@{
    ViewData["Title"] = "Eliminar poste";
}

<div class="bg-secondary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-7">
                            <div class="card shadow-lg border-0 rounded-lg mt-5 mb-5">
                                <div class="card-header">
                                    <h3 class="text-center font-weight-light my-4">Eliminar poste</h3>
                                    @if (ViewData["error_obtener_poste"] is not null)
                                    {
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Ocurri&oacute; un error</h4>
                                            <p>@ViewData["error_obtener_poste"]</p>
                                        </div>
                                        <a asp-action="Index" asp-controller="Postes">Volver</a>
                                    }
                                </div>
                                <div class="card-body">
                                    @if (ViewData["error_obtener_poste"] is null)
                                    {
                                        <div>
                                            <dl class="row">
                                                <dt class="col-sm-2">
                                                    @Html.DisplayNameFor(model => model.Id)
                                                </dt>
                                                <dd class="col-sm-10">
                                                    @Html.DisplayFor(model => model.Id)
                                                </dd>
                                                <dt class="col-sm-2">
                                                    @Html.DisplayNameFor(model => model.Nombre)
                                                </dt>
                                                <dd class="col-sm-10">
                                                    @Html.DisplayFor(model => model.Nombre)
                                                </dd>
                                                
                                            </dl>

                                            <form asp-action="Eliminar" asp-controller="Postes">
                                                <input type="hidden" asp-for="Id" />
                                                <input type="submit" value="Eliminar" class="btn btn-danger" />
                                                <a asp-action="Index" asp-controller="Postes" class="btn btn-secondary">Volver</a>
                                            </form>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</div>

LevantamientoDeRed/Views/Postes/Index.cshtml
@{
    ViewData["Title"] = "Mapa de postes";
}

<div class="container-fluid px-4" style="display: grid">
    <h1 class="mt-4">Mapa de postes</h1>

    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Tablero</a></li>
        <li class="breadcrumb-item active">Mapa de postes</li>
    </ol>

    @if (User.IsInRole("Administrador") || User.IsInRole("Jefe"))
    {
        <div class="btn-group mb-4" role="group" aria-label="Basic mixed styles example">
            <a asp-action="Crear" class="btn btn-success">Crear</a>
            <button id="editarButtonElement" type="button" class="btn btn-info">Editar</button>

            <button id="eliminarButtonElement" type="button" class="btn btn-danger">Eliminar</button>
        </div>
    }
    else if (User.IsInRole("Tecnico"))
    {
        <div class="btn-group mb-4" role="group" aria-label="Basic mixed styles example">
            <a asp-action="Crear" class="btn btn-success">Crear</a>
        </div>
    }
    <div class="btn-group mb-4" role="group" aria-label="Basic mixed styles example">
        <a href="/Mufas" class="btn btn-warning">Ver Mufas</a>
        <a href="/Gpons" class="btn btn-secondary">Ver G-pons</a>

    </div>

    <div class="form-floating mb-4">
        <select id="postesSelectElement" class="form-select">
            <option selected value="0">Todos</option>
        </select>
        <label for="postesSelectElement">Seleccionar</label>
    </div>

    <div class="card">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Mapa de postes
        </div>
        <div class="card-body">
            <div id="map" style="height: 500px"></div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_GoogleMapsScriptsPartial");
        await Html.RenderPartialAsync("_PostesControllerScriptsPartial");
        await Html.RenderPartialAsync("_MufasControllerScriptsPartial");
        await Html.RenderPartialAsync("_GponsControllerScriptsPartial");
    }

    <script async>
        let map;
        let marcadores = [];

        async function initMap() {
            const position = { lat: 13.924394865271614, lng: -89.849635478908 };
            const { Map } = await google.maps.importLibrary("maps");
            const postes = await obtenerPostes();

            map = new Map(document.getElementById("map"), {
                zoom: 15,
                center: position,
                mapId: "DEMO_MAP_ID",
            });

            postes.map((poste) => {
                drawPoste(poste)
            });

            rellenarElementoSelect(postes);

            document.getElementById("postesSelectElement").addEventListener("change", async () => {
                const selectElement = document.getElementById("postesSelectElement");
                //eliminar todos cuando se selecciona 1
                deleteAllMarkers();

                if (selectElement.value === "0") {
                    postes.map((poste) => {
                        drawPoste(poste)
                    });
                } else {
                    const posteFromApi = await obtenerPoste(selectElement.value);

                    drawPoste(posteFromApi);
                }
            });

            document.getElementById("eliminarButtonElement").addEventListener("click", async () => {
                const selectElement = document.getElementById("postesSelectElement");
                const URL_BASE = `${window.location.protocol}//${window.location.hostname}${PORT}/Postes/Eliminar`;

                if (selectElement.value !== "0") {
                    window.location.href = URL_BASE + "/" + selectElement.value;
                }
                else {
                    await Swal.fire(
                        'Advertencia',
                        'Debe seleccionar un poste para realizar esta accion',
                        'warning'
                    )
                }
            });

            document.getElementById("editarButtonElement").addEventListener("click", async () => {
                const selectElement = document.getElementById("postesSelectElement");


                if (selectElement.value !== "0") {
                    showEditPosteModal(selectElement.value);
                }
                else {
                    await Swal.fire(
                        'Advertencia',
                        'Debe seleccionar un poste para realizar esta accion',
                        'warning'
                    )
                }
            });
        }

        function drawPoste(poste) {
            const latLng = {
                lat: poste.latitud,
                lng: poste.longitud
            };
            const imageUrl = "\logo_poste.png";
            const newPoste = new google.maps.Marker({
                position: latLng,
                map: map,
                title: poste.nombre,
                icon: {
                    url: imageUrl,
                    scaledSize: new google.maps.Size(60, 60) // Ajusta el tamaño según tus necesidades
                },
            });
            marcadores.push(newPoste);
        }

        // Elimina todos los marcadores cuando se llama
        function deleteAllMarkers() {
            for (var i = 0; i < marcadores.length; i++) {
                marcadores[i].setMap(null);
            }

            // Limpia el array de marcadores
            marcadores = [];
        }


        async function showEditPosteModal(posteId) {
            let posteToEdit = await obtenerPoste(posteId);

            if (posteToEdit === null) {
                await Swal.fire(
                    'Error',
                    'Los datos del poste no existen o no estan disponibles',
                    'error'
                )

                return;
            }

            const mufas = (await ObtenerMufas()).map((mufa) => {
                if (mufa.id === posteToEdit.mufaId) {
                    return `<option value="${mufa.id}" selected>${mufa.nombre}</option>`;
                }

                return `<option value="${mufa.id}">${mufa.nombre}</option>`;

            }).join();

            const gpons = (await ObtenerGpons()).map((gpon) => {
                if (gpon.id === posteToEdit.gponId) {
                    return `<option value="${gpon.id}" selected>${gpon.nombre}</option>`;
                }

                return `<option value="${gpon.id}">${gpon.nombre}</option>`;
            }).join();

            const { value: formValues } = await Swal.fire({
                title: 'Datos del poste',
                html:
                    // Input del nombre del poste
                    '<div class="form-floating mb-3">' +
                    `<input type="text" value="${posteToEdit.nombre}" class="form-control" id="poste-nombre" placeholder="Ingrese el nombre del poste" required>` +
                    '<label for="floatingInput">Nombre Del Poste</label>' +
                    '</div>' +
                    // Select de mufas
                    '<div class="form-floating mb-3">' +
                    `  <select class="form-select" id="mufas-list">` +
                    '    <option value="">-- No agregar aun --</option>' +
                    mufas +
                    '  </select>' +
                    '  <label for="mufa-list">Seleccione mufa</label>' +
                    '</div>' +
                    // Select de GPONs
                    '<div class="form-floating mb-3">' +
                    `  <select class="form-select" id="gpons-list">` +
                    '    <option value="">-- No agregar aun --</option>' +
                    gpons +
                    '  </select>' +
                    '  <label for="gpons-list">Seleccione GPON</label>' +
                    '</div>',
                focusConfirm: false,
                showCancelButton: true,
                preConfirm: () => {
                    return [
                        document.getElementById('poste-nombre').value,
                        document.getElementById('mufas-list').value,
                        document.getElementById('gpons-list').value,
                    ]
                }
            })

            if (formValues) {

                posteToEdit.nombre = formValues[0];
                posteToEdit.mufaId = formValues[1];
                posteToEdit.gponId = formValues[2];

                await EditarPoste(posteToEdit);
            }
        }

        initMap();
    </script>
}